@startuml State diagram use cases

state "Verificar publicación" as class1
state "Iniciar sesión" as class2
state "Publicar evento" as class3
state "Comentar" as class4
state "Editar evento" as class5
state "Gestionar perfil" as class6
state "Consultar publicaciones" as class7
state "Buscar publicación" as class8
state "Cerrar sesión" as class9
state "Consultar calendario" as class10
state "Ver publicación" as class11
state "Registrar usuario" as class12

[*] --> class7
class7 --> class11: Detallar evento
class11 --> class12: Ingresar datos
class11 --> class2: Ingresar datos
class12 --> class2: Ingresar datos
class2 --> class9: Salir
class2 --> class6: Actualizar datos
class2 --> class3: Subir imagen
class2 --> class7: Detallar eventos
class7 --> class8: Precisar evento
class7 -r-> class4: [solo si el usuario inició sesión]
class7 --> class5: [solo si el usuario inició sesión]
class7 --> class1: [solo si el usuario inició sesión]
class7 --> class10: Conocer eventos
class9 --> [*]

@enduml