@startuml crear evento
actor Usuario
boundary "Vista crear publicación" as c
Usuario--c :1: Crear publicación
control "Gestor de publicaciones" as g
c-r-g :2: Solicitar información
entity "Publicación" as p
g--p :3: Crear
@enduml