@startuml Consultar Calendario
actor User as User

boundary "calendarView" as view
control "consultCalendarController" as controller
entity Event as E
User --> view
view-r->controller : "1: GetCalendar"
controller-->E : "3: GetEventsByMonth"
@enduml