@startuml Consultar Calendario
actor User as User

boundary "Calendar view" as view
control "UC Consult calendar controller" as controller
entity Post as P
User --> view : "1: Consult calendar" 
view-r->controller : "2:"
controller-->P 
@enduml