@startuml consultar publicaciones
actor User
boundary "postsView" as view
User-->view 
control "consultPostsController" as controller
view-r->controller :1: getLatestUploadedPosts()
entity "Post" as P
controller-->P : 2: getPost()
@enduml