@startuml Consultar Calendario
actor Usuario as U

boundary "Vista calendario" as V
control "Gestor de publicaciones" as G
entity Publicación as P
entity Calendario as C

U -- V : "1: Consulta calendario" 
V-r-C :"2: Mostrar"
V -- G : "3: Pedir fecha"
G -r- P : "4: Filtrar publicaciones por fecha"
@enduml