@startuml Cerrar Sessión
actor "Usuario" as U
boundary VistaCerrarSession as V
control Autenticador as C
entity "Usuario" as E

U -- V : "1: Solicita Cerrar Session"
V -- C : ""
C -- E : "3: Invalida Credenciales"

@enduml