@startuml Iniciar Sesion

    actor ":Usuario" as U
    boundary ":Solicitud de datos de ingreso" as SDI
    control ":Gestor de usuario" as GU
    boundary ":Publicaciones" as P
    entity ":Usuario" as UE

    U -r- SDI : "1:iniciar sesion"
    SDI -r- GU : "2:validar"
    GU -r- UE : "3:obtener"
    GU -- P : "4:mostrar"

@enduml