@startuml Buscar publicación
actor User as U

boundary "searchPostView" as V
control "searchPostController" as G
entity Post as P

U -->V : "1: setFilterParameter()" 
V -r-> G : "2: searchPost(filter)"
G --> P : "3: getPost() "
@enduml