@startuml crear evento
actor User
boundary "createPostView" as view
User-->view :1: setPost()
control "createPostController" as controller
view-r->controller :2: createPost()
entity "Post" as entity
controller-->entity :3: newPost()
@enduml