@startuml verificarPublicaciones
actor "Admin user" as Act
boundary "verifyPostView" as view
Act--view
control "verifyPostController" as controller
view-r-controller
entity Post as entity
controller--entity
@enduml