@startuml Analysis Class Diagram
class User{
 +name: String
    +last_Name: String
    +type: String
    +email: String
}
class Post{
 +title: String
    +image: attachment
    +description: String
}
class Profile{}
class profileView{
+showProfile()
+requestData()
}
class ProfileManager{
+editProfile()
+deleteProfile()

}
class Calendar{
    +event_Activity: String
    +date: Date
}
class registView{
   +dataRequest()
}
class userManager{
     +createUser()
     +loginUser()
     +nullify()
}
class loginView{
+dataRequest()
}
class postWallView{
  +showPosts()
  +postViewingRequest()
}
class createPostView{
 +dataRequest()
}
class postManager{
+searchPost()
+showPost()
+deletePost()
+addPost()
}
class postVerificationView{
+showPosts()
+rejectPost()
+approvePost()
}
class calendarView{
+requestSearhData()
}

class logOutView{
+requestLogOut()
}

User <|--Profile
User-- registView
User-- logOutView
logOutView-- userManager
registView-- userManager
User-- loginView
loginView-- userManager
Profile--profileView
profileView--ProfileManager
Post--postWallView
Post-- postVerificationView
Post-- createPostView
Calendar--calendarView
postWallView--postManager
createPostView--postManager
postVerificationView--postManager
calendarView--postManager
User-->Post 
@enduml
