@startuml classDiagram
class user{
 +name: String
    +last_Name: String
    +type: String
    +email: String
}
class Post{
 +title: String
    +image: attachment
    +description: String
    + Author: String
    + showPost()
}
class Calendar{
    +event_Activity: String
    +date: Date
}
class postWallView{
  +postViewingRequest()
}
class createPostView{
 +dataRequest()
}
class postManager{
+filterPostByParameter()
+deletePost()
+addPost()
+ getLatestPost()
}
class postVerificationView{
+rejectPost()
+approvePost()
}
class calendarView{
+requestSearchData()
}
class searchPostView{
  +requestFilterParameter()
  +requestSearchData()
}

Post--postWallView
Post-- postVerificationView
Post-- createPostView
Calendar--calendarView
postWallView--postManager
createPostView--postManager
postVerificationView--postManager
calendarView--postManager
searchPostView--postManager
user-->Post
@enduml
