@startuml classDiagram
class user{
 +name: String
    +last_Name: String
    +type: String
    +email: String
}
class Post{
 +title: String
    +image: attachment
    +description: String
    + author: String
    + approve: bool
    + getPost()
    +newPost()
    +setApprove()


}

class verifyPostController{
+uploadPost()
}
class createPostController{
  +createPost()
}
class consultPostController{
+ getLatestPost()
}
class searchPostController{
+searchPost()
}
class consultCalendarController{
  +searchPostByDate()
}
class verifyPostView{
+approveRejectPost()
}
class calendarView{
}
class postsView{
  
}
class createPostView{
 +setPost()
}
class searchPostView{
  setFilterParameter()
}

user--postsView
user-- verifyPostView
user-- createPostView
user-- searchPostView
postsView--consultPostController
createPostView--createPostController
verifyPostView--verifyPostController
searchPostView--searchPostController
searchPostController--Post
createPostController--Post
verifyPostController--Post
consultPostController--Post
user--calendarView
calendarView--consultCalendarController
@enduml
