@startuml classDiagram

class BuhoSocial{}

class User{
    +name: String
    +last_Name: String
    +type: String
    +email: String
    +login()
    +log_Out()
    +register()
}

class Publication{
    +title: String
    +image: attachment
    +description: String
    +add()
    +edit()
    +consult()
}

class Profile{
    +edit()
    +add()
}

class Comment{
    +date: Date
    +hour: String
    +content: String
    +add()
    +edit()
    +delete()
}

class Calendar{
    +event_Activity: String
    +date: Date
    +consult()
}

Publication --o BuhoSocial
User --o BuhoSocial
Profile --|> User
Profile --> Publication: can see
Comment --o Publication
Publication --> Calendar: can consult

@enduml
