@startuml packageDiagramDescription

allowmixing

package view <<Folder>> {
    class postVerificationView{
        +showPosts()
        +rejectPost()
        +approvePost()
    }
    class calendarView{
        +solicitarDatosBusqueda()
    }

    class logOutView{
        +requestLogOut()
    }
    class postWallView{
        +showPosts()
        +postViewingRequest()
    }
    class createPostView{
        +dataRequest()
    }
    class loginView{
        +dataRequest()
    }
    class registView{
        +dataRequest()
    }
    class profileView{
        +showProfile()
        +requestData()
    }
}

package controllers <<Folder>> {
    class postManager{
        +searchPost()
        +showPost()
        +deletePost()
        +addPost()
    }
    class userManager{
        +createUser()
        +loginUser()
        +nullify()
    }
    class ProfileManager{
        +editProfile()
        +delteProfile()
    }
}

package models <<Folder>> {
    class user{
        +name: String
        +last_Name: String
        +type: String
        +email: String
    }
    class Post{
        +title: String
        +image: attachment
        +description: String
    }
    class Profile{}
    class profileView{
        +showProfile()
        +requestData()
    }
    class Calendar{
        +event_Activity: String
        +date: Date
    }
}


@enduml