@startuml packageDiagramDescription

allowmixing

package views <<Folder>> {
    class VerifyPostView{
+approveRejectPost()
}
class CalendarView{
  +getCalendar()
}
class PostsView{
  +getLatestPost()
}
class CreatePostView{
 +setPost()
}
class SearchPostView{
  setFilterParameter()
}
}
   

package controllers <<Folder>> {
class VerifyPostView{
+approveRejectPost()
}
class CalendarView{
  +getCalendar()
}
class PostsView{
  +getLatestPost()
}
class CreatePostView{
 +setPost()
}
class SearchPostView{
  setFilterParameter()
}
}

package models <<Folder>> {

    class Post{
        +title: String
        +image: attachment
        +description: String
        +author: String
        +approve: bool
    
}
class Event{
  +date: Date 
  +time: Time
  +getEvent()
}
Post<|--Event

class User{
 +name: String
    +last_Name: String
    +type: String
    +email: String
}
}


@enduml