@startuml "Sequence Diagram UC Create Post"
actor User
boundary createPostView
control createPostController
entity Post
activate User
activate createPostView
User->createPostView: setPost()
createPostView->createPostView:fieldCheck()
activate createPostController
createPostView->createPostController:createPost()
deactivate createPostView
activate Post
createPostController->Post: newPost()
Post-->createPostController:putOnVerifiableList()
@enduml