@startuml useCaseDiagram
actor "Personal administrativo" as admin
actor Usuario as user
actor "Usuario no registrado" as userR
left to right direction


rectangle Búho_Social{
    usecase "Iniciar sesión" as UC1
    usecase "Registrar usuario" as UC2
    usecase "Consultar publicaciones" as UC3
    usecase "Publicar evento" as UC4
    usecase "Ver publicación" as UC5
    usecase "Comentar" as UC6
    usecase "Editar evento" as UC7
    usecase "Gestionar perfil" as UC8
    usecase "Cerrar sesión" as UC9
    usecase "Verificar publicación" as UC10
    usecase "Consultar calendario" as UC11
    usecase "Buscar publicación" as UC12
}
admin--UC10
user--UC1
user--UC2
user--UC3
UC12 .u.>UC3 :extend
user--UC4
user--UC5
user--UC6
user--UC7
user--UC8
user--UC9
user--UC11
user <|-- admin
userR--UC3
userR--UC5
userR--UC2
userR--UC11

@enduml