@startuml Modelo de Dominio

left to right direction

class Campus{}
class Estudiante{}
class Profesor{}
class "Personal de apoyo" as class1{}
class Actividad{}
class Seminario{}
class Taller{}
class Carrera{}
class "Grupo de estudio" as class2{}
class Club{}
class Deporte{}
class Cultura{}
class Esparcimiento{}
class "Temas de interes" as class3{}
class Administrador{}
class Técnico{}
class Obrero{}
class Evento{}
class Información{}
class Proyecto{}
class Experiencia{}
class Investigación{}
class "Medios de difusión" as class4{}

Estudiante "1..*" --o Campus
Profesor "1..*" --o Campus
class1 "1..*" --o Campus
Administrador --|> class1
Obrero --|> class1
Técnico --|> class1
Estudiante "1..*" --o Carrera

Seminario --|> Actividad
Taller --|> Actividad
Estudiante -[hidden]-> Actividad
Estudiante -down-> "1..*" Actividad: Organiza
Estudiante --> "1..*" class2: Crea
Estudiante --> "1..*" Club: Forma
Deporte --|> Club
Cultura --|> Club
Esparcimiento--|> Club
class3 --o Club
Administrador --> "1..*" Evento: Promueve

Profesor --> Información:Publica
Proyecto --|> Información
Experiencia --|> Información
Investigación --|> Información

Información --> class4: Se comparte
Evento --> class4: Se comparte
Actividad --> class4: Se comparte
class2 --> class4: Se comparte
Club --> class4: Se comparte

hide members

@enduml
