@startuml Consultar Calendario
actor User as User

boundary "calendarView" as view
control "consultCalendarController" as controller
entity Event as E
User --> view  : "1: getCalendar()"
view-r->controller :"2: getEventsByMonth()"
controller-->E :"3:getEvent()"
@enduml