@startuml verificarPublicaciones
actor "Admin user" as Act
boundary "verifyPostView" as view
Act-->view :1: approveRejectPost()
control "verifyPostController" as controller
view-r->controller :2: uploadPost()
entity Post as entity
controller-->entity :3: setApprove()
@enduml