@startuml verificarPublicaciones
actor "Admin user" as Act
boundary "Verify Post view" as view
Act--view
control "UC verify post controller" as controller
view-r-controller
entity Post as entity
controller--entity
@enduml