@startuml consultar publicaciones
actor User
boundary "Wall Posts view" as view
User--view 
control "UC Consult Posts controller" as controller
view-r-controller 
entity "Post" as P
controller--P 
@enduml