@startuml verificarPublicaciones
actor "Admin user" as Act
boundary "Post to check view" as view
Act--view
control "UC Check posts controller" as controller
view-r-controller
entity Post as entity
controller--entity
@enduml