@startuml Consultar Calendario
actor User as User

boundary "Calendar view" as view
control "UC Calendar Controller" as controller
entity Post as P
User --> view
view-r->controller 
controller-->P 
@enduml