@startuml IniciarSesion

    actor Usuario as U
    boundary "Solicitud de datos de ingreso" as SDI
    control "Gestor de usuario" as GU
    boundary Publicaciones as P
    entity Usuario as UE

    U -r- SDI
    SDI -r- GU
    GU -- P
    GU -r- UE

@enduml