@startuml analysisClassDiagram-Gestionar Perfil

:Usuario:
boundary "Perfil del usuario"
control "Actualizar información"
entity "Información del usuario"

Usuario -- "Perfil del usuario"
"Perfil del usuario" -- "Actualizar información"
"Actualizar información" -- "Información del usuario"


@enduml